site_name: {{cookiecutter.project_name}}
repo_url: https://github.com/{{cookiecutter.author_github_handle}}/{{cookiecutter.project_name}}
site_url: https://{{cookiecutter.author_github_handle}}.github.io/{{cookiecutter.project_name}}
site_description: {{cookiecutter.project_description}}
site_author: {{cookiecutter.author}}
copyright: Maintained by {{cookiecutter.author}}.

theme:
  name: material
  custom_dir: docs/theme
  palette:
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  favicon: assets/images/favicon.ico
  icon:
    logo: svg/favicon
  features:
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link

plugins:
  - search

markdown_extensions:
  - mdx_include
  - admonition
  - codehilite
  - extra
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - toc:
      permalink: "¤"

extra:
  social:
{% if cookiecutter.linkedin_username != "" %}
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/{{cookiecutter.linkedin_username}}
      name: LinkedIn
{%- endif %}
{% if cookiecutter.twitter_username != "" %}
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/{{cookiecutter.twitter_username}}
      name: Twitter
{%- endif %}
{% if cookiecutter.github_username != "" %}
    - icon: fontawesome/brands/github
      link: https://github.com/{{cookiecutter.github_username}}
      name: Github
{%- endif %}
{% if cookiecutter.email != "" %}
    - icon: material/gmail
      link: mailto:{{cookiecutter.email}}
      name: Mail
{%- endif %}
